### PR TITLE
Fixes Variables to correct visibility

### PR DESCRIPTION
**Pull request by bsdtux**
While Reading chapter 8 on properties the text says that grade was suppose to be explicitly private but the code shows it as public while name was actually set to private. 

This PR fixes the visibility of those two instance variables

### CODE REVIEW

**Comment by bsdtux** [comment]
I can try and revert some of those formatting changes back if you would like. Looks like black reformatted alot of that code.

**Comment by IrvKalb** [comment]
Hello and thank you for your comments.  I'm open to discussing this, but I believe the code is correct as written.  In this example, I am using a little "trickery", as explained on the next page (176) in the book.  

As a summary, I am setting the starting grade passed in to the property self.grade (not the instance variable self.__grade).  I'm doing this so that Python calls the second def grade (the setter method).  And this is done so that it can do some additional validation of the starting value (type and range) before setting the actual private instance variable: self.__grade.  

Please let me know if you still think there is a problem.  I'm happy to discuss it further.  

(Also, in this example, I don't really care about self.name vs self.__name)

**Comment by bsdtux** [comment]
> Hello and thank you for your comments. I'm open to discussing this, but I believe the code is correct as written. In this example, I am using a little "trickery", as explained on the next page (176) in the book.
> 
> As a summary, I am setting the starting grade passed in to the property self.grade (not the instance variable self.__grade). I'm doing this so that Python calls the second def grade (the setter method). And this is done so that it can do some additional validation of the starting value (type and range) before setting the actual private instance variable: self.__grade.
> 
> Please let me know if you still think there is a problem. I'm happy to discuss it further.
> 
> (Also, in this example, I don't really care about self.name vs self.__name)

I see your point but I have always felt like trickery isn't a great approach. I looked in all the code bases at work and in the past and any time we use getters and setters the pattern that I am seeing is either instantiate the object using the hidden property to the passed in value or set it to a sane default and force the client to use the getter/setter. The second approach isn't the best for sure because it causes extra work but its was really difficult for even myself to read. 

However with all that said I understand that yes you are forcing the class to uses its own setter validation so technically yes there isn't anything wrong here and we can close the PR if you would like

**Comment by IrvKalb** [comment]
I agree with your comment about trickery - I rarely use it.  In this case, I felt it was justified because I wanted the initial value to go through the same verification that setting a future value would use, and this was a way to do it without writing the same code twice.  

However, as you will see when you get to the end of that chapter, I personally don't use properties in my code at all.  I'm a long time believer in getters and setters.  While I obviously understand the mechanism behind the property in Python, it just doesn't feel right to have client code even appear to set a variable inside an object.  In my opinion, getters and setters make things much more clear without having to resort to any trickery.

**Comment by IrvKalb** [comment]
I hope you enjoy the rest of the book, and feel free to contact me if you run into any other issues.  Irv at furrypants dot com

**Pull request closed without merging**
